namespace AzureIPNetworksGenerator;

internal static class SourceGenerationHelper
{
    internal const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the AzureIPNetworksGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
";

    public const string GenerateIpNetworksAttributeName = "GenerateIpNetworksAttribute";
    public const string GenerateIpNetworksAttributeFullName = "AzureIPNetworksGenerator.GenerateIpNetworksAttribute";
    public const string GenerateIpNetworksAttribute = Header + @"
namespace AzureIPNetworksGenerator;

[System.AttributeUsage(System.AttributeTargets.Class)]
internal class GenerateIpNetworksAttribute : System.Attribute { }
";
}
