name: Update file

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      buildConfiguration: 'Release'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Build
      run: |
        echo "UPDATE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        dotnet build $GITHUB_WORKSPACE/AzureIPNetworksDownloader/AzureIPNetworksDownloader.csproj

    - name: Run
      run: dotnet run $GITHUB_WORKSPACE/AzureIPNetworksDownloader/AzureIPNetworksDownloader.csproj

    - uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update files for service tags ($UPDATE_DATE)'
        title: 'Update files for service tags $(UPDATE_DATE)'
