name: Update ServiceTag files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 21 * *'

jobs:
  Run:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      UPDATE_DATE: 'overriden by run action'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Run
        run: |
          echo "UPDATE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          dotnet run --project ${{ github.workspace }}/AzureIPNetworksDownloader/AzureIPNetworksDownloader.csproj --framework net8.0

      - name: Create PR if necessary
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          commit-message: 'Update files for service tags as of ${{ env.UPDATE_DATE }}'
          title: 'Update files for service tags as of ${{ env.UPDATE_DATE }}'
          branch: update-service-tags
          signoff: true
          body: |
            Update files for service tags.

            These files are pulled from the Microsoft website using the downloader project.

            Date: ${{ env.UPDATE_DATE }}
          delete-branch: true
          sign-commits: true
