name: Update ServiceTag files

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/update-files.yml'
  schedule:
    - cron: '0 0 21 * *'

permissions:
  contents: read

jobs:
  Run:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Current date
        id: current-date
        uses: mburumaxwell/actions/current-date@main

      - name: Run
        run: >
          dotnet run
          --framework net9.0
          --project ${{ github.workspace }}/AzureIPNetworksDownloader/AzureIPNetworksDownloader.csproj

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID_RELEASER }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY_RELEASER }}
          permission-contents: write
          permission-pull-requests: write

      - name: Create pull request
        if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: main
          commit-message: 'Update files for service tags as of ${{ steps.current-date.outputs.date }}'
          title: 'Update files for service tags as of ${{ steps.current-date.outputs.date }}'
          branch: update-service-tags
          signoff: true
          body: |
            Update files for service tags.

            These files are pulled from the Microsoft website using the downloader project.

            Date: ${{ steps.current-date.outputs.date }}
          delete-branch: true
          sign-commits: true
