name: Update ServiceTag files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  Run:
    runs-on: ubuntu-latest
    env:
      buildConfiguration: 'Release'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Run
      run: |
        echo "UPDATE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        dotnet run --project $GITHUB_WORKSPACE/AzureIPNetworksDownloader/AzureIPNetworksDownloader.csproj --framework net7.0

    - name: Create PR if necessary
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update files for service tags as of ${{env.UPDATE_DATE}}'
        title: 'Update files for service tags as of ${{env.UPDATE_DATE}}'
        branch: update-service-tags
        signoff: true
